### ISSUE TITLE
Top level unknown encoding should result in OpaqueEncoding

### ISSUE THREAD

**Issue by robert3005** [vortex-data/vortex#1003]
Currently it only happens when asking for children. The annoying part of this change is that the error message will not be the best

**Comment by gatesn** [comment]
This should be fixed now with ArrayParts

**Comment by robert3005** [comment]
This is not fixed, this issue is about difference in behaviour between ArrayData::try_new_viewed and ArrayData::child
